version: '3'
services:
  react_client:
    build:
      dockerfile: Dockerfile.dev
      context: ./config
    ports:
      '3000:3000'
    volumes:
      - /app/node_modules
      - ./client:/app
    server:
      build:
        dockerfile: Dockerfile.dev
        context: .
      ports:
        '5000:5000'
      volumes:
        - /app/node_modules
        - ./:/app
