version: '3'
services:
  nginx:
    restart: always
    build: ./nginx
    ports:
      - '3050:80'
  devconnectnodeserver:
    build: ./server
    volumes:
      - /app/node_modules
      - ./server:/app
  devconnectreactclient:
    build: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
  
  